### ISSUE TITLE
All auto-completion problems

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/ocaml-lsp#943]
An umbrella issue for auto-completion problems:

- [ ] Doesn't work with incorrect suffix - #838 
- [ ] Doesn't work for record fields - https://github.com/ocamllabs/vscode-ocaml-platform/issues/956
- [ ] Doesn't work for named arguments

given

```ocaml 
let aux acc x = acc + x in 
List.fold_left [1; 2; 3] ~init:0 ~f:<|>
```

should olsp offer completion? Currently, one can circumvent the problem by using a typed hole `~f:_` will offer suggestions to fill the hole.

**Comment by copy** [comment]
After `!`, ocaml-lsp should offer to complete references, but it offers operators starting with `!` (technically fine, but the former behavior is mostly what you want when typing `!`). If you put a space after `!` it works.

**Comment by sidkshatriya** [comment]
- [ ] Doesn't autocomplete OCaml object methods. Though this is downstream issue with merlin. See https://github.com/ocaml/merlin/issues/1575
